/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in version control so
// TypeScript can resolve Next-specific types before the first local dev run.
